name: Node Continuous Integration

on:
  pull_request:
    branches: [main, dev]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out the branch
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install node packages
        # consider use --check-cache if needed
        run: pnpm install

      - name: Lint
        run: pnpm lint
        env:
          CI: true